#name: entemarket_user
#description: A new Flutter project.
#
## The following line prevents the package from being accidentally published to
## pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
## The following defines the version and build number for your application.
## A version number is three numbers separated by dots, like 1.2.43
## followed by an optional build number separated by a +.
## Both the version and the builder number may be overridden in flutter
## build by specifying --build-name and --build-number, respectively.
## In Android, build-name is used as versionName while build-number used as versionCode.
## Read more about Android versioning at https://developer.android.com/studio/publish/versioning
## In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
## Read more about iOS versioning at
## https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.2+10
#
#environment:
#  sdk: ">=2.16.1 <3.0.0"
#
## Dependencies specify other packages that your package needs in order to work.
## To automatically upgrade your package dependencies to the latest versions
## consider running `flutter pub upgrade --major-versions`. Alternatively,
## dependencies can be manually updated by changing the version numbers below to
## the latest version available on pub.dev. To see which dependencies have newer
## versions available, run `flutter pub outdated`.
#dependencies:
#  flutter:
#    sdk: flutter
#
#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.2
#  http: ^0.13.3
#  sizer: ^2.0.15
#  shared_preferences: ^2.0.5
#  connectivity: ^3.0.6
#  jaguar_jwt: ^3.0.0
#  image_picker: ^0.8.6
#  flutter_local_notifications: ^9.0.0
#  path_provider: ^2.0.2
#  firebase_messaging: ^10.0.4
#  flutter_rating_bar: ^4.0.0
#  flutter_html: ^2.2.1
#  photo_view: ^0.13.0
#  firebase_auth: ^3.0.1
#  sms_autofill: ^2.0.1
#  intl: 0.17.0
#  country_code_picker: ^2.0.1
#  google_maps_flutter: ^2.0.6
#  fluttertoast: ^8.0.9
#  geolocator: ^8.2.0
#  file_picker: ^4.0.0
#  shimmer: ^2.0.0
#  geocoding: ^2.0.1
#  razorpay_flutter: ^1.2.7
# # flutter_paystack: ^1.0.5+1
#  flutter_html_to_pdf: ^0.7.0
#  permission_handler: ^8.2.2
#  in_app_review: ^2.0.2
#  firebase_dynamic_links: ^2.0.7
#  open_file: ^3.0.3
#  provider: ^6.0.0
#  #stripe_payment: ^1.1.4
#  video_player: ^2.1.5
#  flutter_svg: ^0.22.0
#  paytm: ^3.0.1
#  youtube_player_flutter: ^8.0.0
#  share: ^2.0.4
#  package_info: ^2.0.2
#  url_launcher: ^6.0.3
#  version: ^2.0.0
#  location: ^4.4.0
#  geocoder: ^0.2.1
#  google_maps_place_picker_mb: ^2.0.0-mb.16
##  flutter_downloader: ^1.6.1
# # speech_to_text: ^5.0.0
#  tuple: ^2.0.0
#  cached_network_image: ^3.1.0
#  google_sign_in: ^5.4.2
#  carousel_slider: ^4.0.0
#  dropdown_button2: ^1.2.0
#  flutter_firebase_chat_core: ^1.5.4
#  flutter_chat_types: ^3.3.4
#  flutter_chat_ui: ^1.5.8
#  flutter_login_facebook: ^1.4.1
#  flutter_facebook_auth: ^4.3.0
#  downloads_path_provider_28: ^0.1.2
##  downloads_path_provider_28: ^0.1.2
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
#  flutter_lints: ^1.0.0
#    # For information on the generic Dart part of this file, see the
## following page: https://dart.dev/tools/pub/pubspec
#
## The following section is specific to Flutter.
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true
#
#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/images/
#    - lib/Language/
#    - assets/logo/
#    - assets/new_img/
#    - assets/icons/
#
#  fonts:
#    - family: opensans
#      fonts:
#        - asset: assets/font/OpenSans-Regular.ttf


name: vezi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  sizer: ^2.0.15
  shared_preferences: ^2.0.5
  connectivity: ^3.0.6
  jaguar_jwt: ^3.0.0
  image_picker: ^0.8.6
  flutter_local_notifications: ^9.8.0+1
  path_provider: ^2.0.2
  firebase_messaging: ^14.2.0
  flutter_rating_bar: ^4.0.0
  firebase_auth: ^4.2.3
  flutter_html: ^2.2.1
  photo_view: ^0.13.0
  cc_avenue: ^1.0.3
#  firebase_auth: ^3.0.1
  sms_autofill: ^2.0.1
  firebase_dynamic_links: ^5.0.10
  intl: 0.17.0
  firebase_core: ^2.4.0
  country_code_picker: ^2.0.1
  google_maps_flutter: ^2.0.6
  geolocator: ^9.0.2
  fluttertoast: ^8.0.9
#  geolocator: ^8.2.0
  file_picker: ^4.0.0
  shimmer: ^2.0.0
  geocoding: ^2.0.1
  razorpay_flutter: ^1.2.7
  # flutter_paystack: ^1.0.5+1
  flutter_html_to_pdf: ^0.7.0
#  permission_handler: ^8.2.2
  in_app_review: ^2.0.2
  open_filex: ^3.4.0
  provider: ^6.0.0
  #stripe_payment: ^1.1.4
  video_player: ^2.1.5
  permission_handler: ^10.2.0
  flutter_svg: ^0.22.0
  paytm: ^3.0.1
  youtube_player_flutter: ^8.0.0
  share: ^2.0.4
  package_info: ^2.0.2
  url_launcher: ^6.0.3
  version: ^2.0.0
  location: ^4.4.0
  geocoder: ^0.2.1
  flutter_inappwebview: ^5.3.2
  google_maps_place_picker_mb: ^2.0.0-mb.16
#  flutter_downloader: ^1.6.1
  # speech_to_text: ^5.0.0
  tuple: ^2.0.0
  cached_network_image: ^3.1.0
  google_sign_in: ^5.4.2
  carousel_slider: ^4.0.0
  dropdown_button2: ^1.2.0
  flutter_firebase_chat_core: ^1.6.4
  flutter_chat_types: ^3.3.4
  flutter_chat_ui: ^1.5.8
  flutter_login_facebook: ^1.4.1
  flutter_facebook_auth: ^4.3.0
  downloads_path_provider_28:
      path: ./downloads_path_provider


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0
  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/Language/
    - assets/logo/
    - assets/new_img/
    - assets/icons/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf